// pipeline {
//     agent any
//
//     tools {
//         // Install the Maven version configured as "M3" and add it to the path.
//         maven "Maven"
//         jdk "JDK19"
//     }
//
//     stages {
//         stage('Build') {
//             steps {
//                 // Get some code from a GitHub repository
//                 git branch: 'main', url: 'https://github.com/mlvncnxx/COMP367-Lab2.git'
//
//                 // Run Maven on a Unix agent.
//                 sh "mvn -Dmaven.test.failure.ignore=true clean package"
//
//                 // To run Maven on a Windows agent, use
//                  //bat "mvn clean compile"
//             }
//         }
//     }
// }

pipeline {
    agent any

    tools {
        maven "Maven"
        jdk "JDK19"
    }

    stages {
        stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/mlvncnxx/COMP367-Lab2.git'

                withEnv(['/Library/Java/JavaVirtualMachines/openjdk-19.0.1.jdk/Contents/Home/bin']) {
                    sh "mvn -Dmaven.test.failure.ignore=true clean package"
                }
            }
        }
    }
}
